.TH MULTIPATH.CONF 5 2016-07-06 "Linux"
.SH NAME
multipath.conf \- multipath daemon configuration file
.SH DESCRIPTION
.B "multipath.conf"
is the configuration file for the multipath daemon. It is used to
overwrite the built-in configuration table of \fBmultipathd\fP.
Any line whose first non-white-space character is a '#' is considered
a comment line. Empty lines are ignored.
.SH SYNTAX
The configuration file contains entries of the form:
.RS
.nf
.ft B
.sp
<section> {
.RS
.ft B
<attribute> <value>
.I "..."
.ft B
<subsection> {
.RS
.ft B
<attribute> <value>
.I "..."
.RE
.ft B
}
.RE
.ft B
}
.ft R
.fi
.RE
.LP
Each \fIsection\fP contains one or more attributes or subsections. The
recognized keywords for attributes or subsections depend on the
section in which they occur.
.LP
The following \fIsection\fP keywords are recognized:
.TP 17
.B defaults
This section defines default values for attributes which are used
whenever no values are given in the appropriate device or multipath
sections.
.TP
.B blacklist
This section defines which devices should be excluded from the
multipath topology discovery.
.TP
.B blacklist_exceptions
This section defines which devices should be included in the
multipath topology discovery, despite being listed in the
.I blacklist
section.
.TP
.B multipaths
This section defines the multipath topologies. They are indexed by a
\fIWorld Wide Identifier\fR(wwid). For details on the wwid generation
see section \fIWWID generation\fR below.
.TP
.B devices
This section defines the device-specific settings.
.TP
.B overrides
This section defines values for attributes that should override the
device-specific settings for all devices.
.RE
.LP
.SH "defaults section"
The
.I defaults
section recognizes the following keywords:
.TP 17
.B polling_interval
interval between two path checks in seconds. For properly functioning paths,
the interval between checks will gradually increase to
.I max_polling_interval.
This value will be overridden by the
.I WatchdogSec
setting in the multipathd.service definition if systemd is used.
.RS
.TP
Default value is: \fB5\fR
.RE
.TP
.B max_polling_interval
maximal interval between two path checks in seconds.
.RS
.TP
Default value is: \fB4 * polling_interval\fR
.RE
.TP
.B multipath_dir
directory where the dynamic shared objects are stored.
.RS
.TP
Default value is: \fB<system dependent>\fR, commonly /lib64/multipath/
.RE
.TP
.B find_multipaths
If set to
.I yes
, instead of trying to create a multipath device for every non-blacklisted
path, multipath will only create a device if one of three condidions are
met.
.I 1
There are at least two non-blacklisted paths with the same wwid,
.I 2
the user manually forces the creation, by specifying a device with the multipath
command, or
.I 3
a path has the same WWID as a multipath device that was previously created
while find_multipaths was set (even if that multipath device doesn't currently
exist).
Whenever a multipath device is created with find_multipaths set, multipath will
remeber the WWID of the device, so that it will automatically create the
device again, as soon as it sees a path with that WWID. This should allow most
users to have multipath automatically choose the correct paths to make into
multipath devices, without having to edit the blacklist.
.RS
.TP
Default value is: \fBno\fR
.RE
.TP
.B verbosity
default verbosity. Higher values increase the verbosity level. Valid
levels are between 0 and 6.
.RS
.TP
Default value is: \fB2\fR
.RE
.TP
.B reassign_maps
enable reassigning of device-mapper maps. With this option multipathd
will remap existing device-mapper maps to always point to multipath
device, not the underlying block devices. Possible values are
\fIyes\fR and \fIno\fR.
.RS
.TP
Default value is: \fBno\fR
.RE
.TP
.B path_selector
The default path selector algorithm to use; they are offered by the
kernel multipath target. There are three selector algorithms.
.RS
.TP 12
.I "round-robin 0"
Loop through every path in the path group, sending the same amount of IO to
each.
.TP
.I "queue-length 0"
Send the next bunch of IO down the path with the least amount of outstanding IO.
.TP
.I "service-time 0"
Choose the path for the next bunch of IO based on the amount of outstanding IO
to the path and its relative throughput.
.TP
Default value is: \fBservice-time 0\fR
.RE
.TP
.B path_grouping_policy
The default path grouping policy to apply to unspecified
multipaths. Possible values are
.RS
.TP 12
.I failover
1 path per priority group
.TP
.I multibus
all paths in 1 priority group
.TP
.I group_by_serial
1 priority group per serial number
.TP
.I group_by_prio
1 priority group per priority value. Priorities are determined by
callout programs specified as a global, per-controller or
per-multipath option in the configuration file.
.TP
.I group_by_node_name
1 priority group per target node name. Target node names are fetched
in /sys/class/fc_transport/target*/node_name.
.TP
Default value is: \fBfailover\fR
.RE
.TP
.B uid_attribute
The udev attribute providing a unique path identifier.
.RS
.TP
Default value is: \fBID_SERIAL\fR
.RE
.TP
.B getuid_callout
The default program and args to callout to obtain a unique path
identifier. Should be specified with an absolute path.
This parameter is deprecated.
.TP
.B prio
The name of the path priority routine. The specified routine
should return a numeric value specifying the relative priority
of this path. Higher number have a higher priority.
.I "none"
is a valid value. Currently the following path priority routines
are implemented:
.RS
.TP 12
.I const
Return a constant priority of \fI1\fR.
.TP
.I emc
Generate the path priority for DGC class arrays as CLARiiON CX/AX and
EMC VNX families.
.TP
.I alua
Generate the path priority based on the SCSI-3 ALUA settings. This prioritizer
accepts the optional prio_arg
.I exclusive_pref_bit
.TP
.I ontap
Generate the path priority for NetApp ONTAP class and OEM arrays as IBM NSeries.
.TP
.I rdac
Generate the path priority for LSI/Engenio/NetApp E-Series RDAC controller.
.TP
.I hp_sw
Generate the path priority for Compaq/HP controller in
active/standby mode.
.TP
.I hds
Generate the path priority for Hitachi HDS Modular storage arrays.
.TP
.I random
Generate a random priority between 1 and 10.
.TP 12
.I weightedpath
Generate the path priority based on the regular expression and the
priority provided as argument. requires prio_args keyword.
.TP
Default value is: \fBconst\fR
.RE
.TP
.B prio_args
Arguments to pass to to the prio function. This only applies to certain
prioritizers
.RS
.TP 12
.I weighted
Needs a value of the form
.I "<hbtl|devname|wwn> <regex1> <prio1> <regex2> <prio2> ..."
.I hbtl
regex can be of SCSI H:B:T:L format  Ex: 1:0:.:. , *:0:0:.
.I devname
regex can be of device name format  Ex: sda , sd.e
.I wwn
regex can be of the form
.I "host_wwnn:host_wwpn:target_wwnn:target_wwpn"
these values can be looked up through sysfs or by running
.I mulitpathd show paths format "%N:%R:%n:%r" Ex: 0x200100e08ba0aea0:0x210100e08ba0aea0:.*:.* , .*:.*:iqn.2009-10.com.redhat.msp.lab.ask-06:.*
.TP
.I alua
If
.I exclusive_pref_bit
is set, paths with the TPGS pref bit set will always be in their own path
group.
.TP
Default value is: \fB<unset>\fR
.RE
.TP
.B features
Specify any device-mapper features to be used. Syntax is
.I num list
where
.I num
is the number of features in
.I list.
Possible values for the feature list are
.RS
.TP 12
.I queue_if_no_path
Queue IO if no path is active; identical to the
.I no_path_retry
keyword.
.TP
.I no_partitions
Disable automatic partitions generation via kpartx.
.TP
Default value is: \fB0\fR
.RE
.TP
.B path_checker
The default method used to determine the paths state. Possible values
are
.RS
.TP 12
.I readsector0
(Deprecated) Read the first sector of the device. This checker is being
deprecated, please use \fItur\fR instead
.TP
.I tur
Issue a
.I TEST UNIT READY
command to the device.
.TP
.I emc_clariion
Query the DGC/EMC specific EVPD page 0xC0 to determine the path state
for CLARiiON CX/AX and EMC VNX arrays families.
.TP
.I hp_sw
Check the path state for HP storage arrays with Active/Standby firmware.
.TP
.I rdac
Check the path state for LSI/Engenio/NetApp E-Series RDAC storage controller.
.TP
.I directio
(Deprecated) Read the first sector with direct I/O. This checker is being
deprecated, it will cause spurious path failures under high load.
Please use \fItur\fR instead.
.TP
Default value is: \fBtur\fR
.RE
.TP
.B alias_prefix
The \fIuser_friendly_names\fR prefix.
.RS
.TP
Default value is: \fBmpath\fR
.RE
.TP
.B failback
Tell multipathd how to manage path group failback.
.RS
.TP 12
.I immediate
Immediately failback to the highest priority pathgroup that contains
active paths.
.TP
.I manual
Do not perform automatic failback.
.TP
.I followover
Only perform automatic failback when the first path of a pathgroup
becomes active. This keeps a node from automatically failing back when
another node requested the failover.
.TP
.I values > 0
deferred failback (time to defer in seconds)
.TP
Default value is: \fBmanual\fR
.RE
.TP
.B  rr_min_io
The number of IO to route to a path before switching to the next in
the same path group. This is only for BIO based multipath.
.RS
.TP
Default value is: \fB1000\fR
.RE
.TP
.B rr_min_io_rq
The number of IO requests to route to a path before switching to the
next in the same path group. This is only for request based multipath.
.RS
.TP
Default value is: \fB1\fR
.RE
.TP
.B rr_weight
If set to \fIpriorities\fR the multipath configurator will assign
path weights as "path prio * rr_min_io". Possible values are
.I priorities
or
.IR uniform .
.RS
.TP
Default value is: \fBuniform\fR
.RE
.TP
.B no_path_retry
Specify the number of retries until disable queueing, or
.I fail
for immediate failure (no queueing),
.I queue
for never stop queueing. If unset no queueing is attempted.
.RS
.TP
Default value is: \fB<unset>\fR
.RE
.TP
.B user_friendly_names
If set to
.I yes
, using the bindings file
.I /etc/multipath/bindings
to assign a persistent and unique alias to the multipath, in the form of mpath<n>.
If set to
.I no
use the WWID as the alias. In either case this be will
be overridden by any specific aliases in the \fImultipaths\fR section.
.RS
.TP
Default value is: \fBno\fR
.RE
.TP
.B flush_on_last_del
If set to
.I yes
, multipathd will disable queueing when the last path to a device has been
deleted.
.RS
.TP
Default value is: \fBno\fR
.RE
.TP
.B max_fds
Specify the maximum number of file descriptors that can be opened by multipath
and multipathd.  This is equivalent to ulimit \-n. A value of \fImax\fR will set
this to the system limit from /proc/sys/fs/nr_open. If this is not set, the
maximum number of open fds is taken from the calling process. It is usually
1024. To be safe, this should be set to the maximum number of paths plus 32,
if that number is greated than 1024.
.RS
.TP
Default value is: \fBmax\fR
.RE
.TP
.B checker_timeout
Specify the timeout to use for path checkers and prioritizers that issue scsi
commands with an explicit timeout, in seconds.
.RS
.TP
Default value is: in \fB/sys/block/sd<x>/device/timeout\fR
.RE
.TP
.B fast_io_fail_tmo
Specify the number of seconds the scsi layer will wait after a problem has been
detected on a FC remote port before failing IO to devices on that remote port.
This should be smaller than dev_loss_tmo. Setting this to
.I off
will disable the timeout.
.RS
.TP
Default value is: in \fB5\fR
.RE
.TP
.B dev_loss_tmo
Specify the number of seconds the scsi layer will wait after a problem has
been detected on a FC remote port before removing it from the system. This
can be set to "infinity" which sets it to the max value of 2147483647
seconds, or 68 years. It will be automatically adjusted to the overall
retry interval
\fIno_path_retry\fR * \fIpolling_interval\fR
if a number of retries is given with \fIno_path_retry\fR and the
overall retry interval is longer than the specified \fIdev_loss_tmo\fR value.
The linux kernel will cap this value to \fI300\fR if \fIfast_io_fail_tmo\fR
is not set.
.RS
.TP
Default value is: \fB600\fR
.RE
.TP
.B queue_without_daemon
If set to
.I no
, when multipathd stops, queueing will be turned off for all devices.
This is useful for devices that set no_path_retry.  If a machine is
shut down while all paths to a device are down, it is possible to hang waiting
for IO to return from the device after multipathd has been stopped. Without
multipathd running, access to the paths cannot be restored, and the kernel
cannot be told to stop queueing IO. Setting queue_without_daemon to
.I no
, avoids this problem.
.RS
.TP
Default value is: \fBno\fR
.RE
.TP
.B bindings_file
The full pathname of the binding file to be used when the user_friendly_names option is set.
.RS
.TP
Default value is: \fB/etc/multipath/bindings\fR
.RE
.TP
.B wwids_file
The full pathname of the wwids file, which is used by multipath to keep track
of the wwids for LUNs it has created multipath devices on in the past.
.RS
.TP
Default value is: \fB/etc/multipath/wwids\fR
.RE
.TP
.B log_checker_err
If set to
.I once
, multipathd logs the first path checker error at logging level 2. Any later
errors are logged at level 3 until the device is restored. If set to
.I always
, multipathd always logs the path checker error at logging level 2.
.RS
.TP
Default value is: \fBalways\fR
.RE
.TP
.B reservation_key
This is the service action reservation key used by mpathpersist.  It must be
set for all multipath devices using persistent reservations, and it must be
the same as the RESERVATION KEY field of the PERSISTENT RESERVE OUT parameter
list which contains an 8-byte value provided by the application client to the
device server to identify the I_T nexus.
.RS
.TP
Default value is: \fB<unset>\fR
.RE
.TP
.B retain_attached_hw_handler
If set to
.I yes
and the scsi layer has already attached a hardware_handler to the device,
multipath will not force the device to use the hardware_handler specified by
mutipath.conf. If the scsi layer has not attached a hardware handler,
multipath will continue to use its configured hardware handler.
.RS
.TP
Default value is: \fBno\fR
.RE
.TP
.B detect_prio
If set to
.I yes
, multipath will try to detect if the device supports ALUA. If so, the device
will automatically use the
.I alua
prioritizer. If not, the prioritizer will be selected as usual.
.RS
.TP
Default value is: \fBno\fR
.RE
.TP
.B force_sync
If set to
.I yes
, multipathd will call the path checkers in sync mode only.  This means that
only one checker will run at a time.  This is useful in the case where many
multipathd checkers running in parallel causes significant CPU pressure.
.RS
.TP
Default value is: \fBno\fR
.RE
.TP
.B deferred_remove
If set to
.I yes
, multipathd will do a deferred remove instead of a regular remove when the
last path device has been deleted.  This means that if the multipath device is
still in use, it will be freed when the last user closes it.  If path is added
to the multipath device before the last user closes it, the deferred remove
will be canceled.
.RS
.TP
Default value is: \fBno\fR
.RE
.TP
.B partition_delimiter
If this value is not set, when multipath renames a device, it will act just
like the kpartx default does, only adding a \fI"p"\fR to names ending in a
number. If this parameter is set, multipath will act like kpartx does with
the \fI-p\fR option is used, and always add delimiter.
.RS
.TP
Default value is: \fB<unset>\fR
.RE
.TP
.B config_dir
If set to anything other than "", multipath will search this directory
alphabetically for file ending in ".conf" and it will read configuration
information from them, just as if it was in /etc/multipath.conf.  config_dir
must either be "" or a fully qualified directory name.
.RS
.TP
Default value is: \fB/etc/multipath/conf.d/\fR
.RE
.TP
.B delay_watch_checks
If set to a value greater than 0, multipathd will watch paths that have
recently become valid for this many checks.  If they fail again while they are
being watched, when they next become valid, they will not be used until they
have stayed up for
.I delay_wait_checks
checks.
.RS
.TP
Default value is: \fBno\fR
.RE
.TP
.B delay_wait_checks
If set to a value greater than 0, when a device that has recently come back
online fails again within
.I delay_watch_checks
checks, the next time it comes back online, it will marked and delayed, and not
used until it has passed
.I delay_wait_checks
checks.
.RS
.TP
Default value is: \fBno\fR
.RE
.TP
.B strict_timinig
If set to
.I yes
, multipathd will start a new path checker loop after exactly one second,
so that each path check will occur at exactly
.I polling_interval
seconds. On busy systems path checks might take longer than one second;
here the missing ticks will be accounted for on the next round.
A warning will be printed if path checks take longer than
.I polling_interval
seconds.
.RS
.TP
Default value is: \fBno\fR
.RE
.TP
.B uxsock_timeout
CLI receive timeout in milliseconds. For larger systems CLI commands
might timeout before the multipathd lock is released and the CLI command
can be processed. This will result in errors like
"timeout receiving packet" to be returned from CLI commands.
In these cases it is recommended to increase the CLI timeout to avoid
those issues.
.RS
.TP
Default value is: \fB1000\fR
.RE
.TP
.B missing_uev_wait_timeout
Controls how many seconds multipathd will wait, after a new multipath device
is created, to receive a change event from udev for the device, before
automatically enabling device reloads. Usually multipathd will delay reloads
on a device until it receives a change uevent from the initial table load.
.RS
.TP
Default value is: \fB30\fR
.RE
.
.SH "blacklist section"
The
.I blacklist
section is used to exclude specific device from inclusion in the
multipath topology. It is most commonly used to exclude local disks or
LUNs for the array controller.
.LP
The following keywords are recognized:
.TP 17
.B wwid
The \fIWorld Wide Identification\fR of a device.
.TP
.B devnode
Regular expression of the device nodes to be excluded.
.TP
.B property
Regular expression of the udev property to be excluded.
.TP
.B device
Subsection for the device description. This subsection recognizes the
.B vendor
and
.B product
keywords. For a full description of these keywords please see the
.I devices
section description.
.SH "blacklist_exceptions section"
The
.I blacklist_exceptions
section is used to revert the actions of the
.I blacklist
section, ie to include specific device in the
multipath topology. This allows one to selectively include devices which
would normally be excluded via the
.I blacklist
section.
.LP
The following keywords are recognized:
.TP 17
.B wwid
The \fIWorld Wide Identification\fR of a device.
.TP
.B property
Regular expression of the udev property to be whitelisted.
.RS
.TP
Default value is: \fB(ID_WWN|SCSI_IDENT_.*)\fR
.RE
.TP
.B devnode
Regular expression of the device nodes to be whitelisted.
.TP
.B device
Subsection for the device description. This subsection recognizes the
.B vendor
and
.B product
keywords. For a full description of these keywords please see the
.I devices
section description.
.LP
The
.I property
blacklist and whitelist handling is different from the usual handling
in the sense that the whitelist
.I has
to be set, otherwise the device will be blacklisted.
In these cases the message
.I blacklisted, udev property missing
will be displayed.
.SH "multipaths section"
The only recognized attribute for the
.I multipaths
section is the
.I multipath
subsection.
.LP
The
.I multipath
subsection recognizes the following attributes:
.TP 17
.B wwid
Index of the container. Mandatory for this subsection.
.TP
.B alias
(Optional) symbolic name for the multipath map.
.LP
The following attributes are optional; if not set the default values
are taken from the
.I defaults
or
.I devices
section:
.sp 1
.PD .1v
.RS
.TP 18
.B path_grouping_policy
.TP
.B path_selector
.TP
.B prio
.TP
.B prio_args
.TP
.B failback
.TP
.B rr_weight
.TP
.B flush_on_last_del
.TP
.B no_path_retry
.TP
.B rr_min_io
.TP
.B rr_min_io_rq
.TP
.B features
.TP
.B reservation_key
.TP
.B deferred_remove
.TP
.B delay_watch_checks
.TP
.B delay_wait_checks
.RE
.PD
.LP
.SH "devices section"
The only recognized attribute for the
.I devices
section is the
.I device
subsection.
.LP
The
.I device
subsection recognizes the following attributes:
.TP 17
.B vendor
(Mandatory) Vendor identifier
.TP
.B product
(Mandatory) Product identifier
.TP
.B revision
(Optional) Revision identfier
.TP
.B product_blacklist
(Optional) Product strings to blacklist for this vendor
.TP
.B alias_prefix
(Optional) The user_friendly_names prefix to use for this
device type, instead of the default "mpath"
.TP
.B hardware_handler
(Optional) The hardware handler to use for this device type.
The following hardware handler are implemented:
.RS
.TP 12
.I 1 emc
Hardware handler for DGC class arrays as CLARiiON CX/AX and EMC VNX families.
.TP
.I 1 rdac
Hardware handler for LSI/Engenio/NetApp E-Series RDAC storage controller.
.TP
.I 1 hp_sw
Hardware handler for Compaq/HP storage arrays in active/standby
mode.
.TP
.I 1 alua
Hardware handler for SCSI-3 ALUA compatible arrays.
.RE
.LP
The following attributes are optional; if not set the default values
are taken from the
.I defaults
section:
.sp 1
.PD .1v
.RS
.TP 18
.B path_grouping_policy
.TP
.B uid_attribute
.TP
.B path_selector
.TP
.B path_checker
.TP
.B prio
.TP
.B prio_args
.TP
.B features
.TP
.B failback
.TP
.B rr_weight
.TP
.B no_path_retry
.TP
.B rr_min_io
.TP
.B rr_min_io_rq
.TP
.B fast_io_fail_tmo
.TP
.B dev_loss_tmo
.TP
.B flush_on_last_del
.TP
.B retain_attached_hw_handler
.TP
.B detect_prio
.TP
.B deferred_remove
.TP
.B delay_watch_checks
.TP
.B delay_wait_checks
.RE
.PD
.LP
.SH "overrides section"
The overrides section recognizes the following optional attributes; if not set
the values are taken from the
.I devices
or
.I defaults
sections:
.sp 1
.PD .1v
.RS
.TP 18
.B path_grouping_policy
.TP
.B uid_attribute
.TP
.B getuid_callout
.TP
.B path_selector
.TP
.B path_checker
.TP
.B alias_prefix
.TP
.B features
.TP
.B prio
.TP
.B prio_args
.TP
.B failback
.TP
.B rr_weight
.TP
.B no_path_retry
.TP
.B rr_min_io
.TP
.B rr_min_io_rq
.TP
.B flush_on_last_del
.TP
.B fast_io_fail_tmo
.TP
.B dev_loss_tmo
.TP
.B user_friendly_names
.TP
.B retain_attached_hw_handler
.TP
.B detect_prio
.TP
.B deferred_remove
.TP
.B delay_watch_checks
.TP
.B delay_wait_checks
.RE
.PD
.LP
.SH "WWID generation"
Multipath uses a \fIWorld Wide Identification\fR (wwid) to determine
which paths belong to the same device. Each path presenting the same
wwid is assumed to point to the same device.
.LP
The wwid is generated by three methods (in the order of preference):
.TP 17
.B getuid_callout
Use the specified external program; cf \fIgetuid_callout\fR above.
Care should be taken when using this method; the external program
needs to be loaded from disk for execution, which might lead to
deadlock situations in an all-paths-down scenario.
.TP
.B uid_attribute
Use the value of the specified udev attribute; cf \fIuid_attribute\fR
above. This method is preferred to \fIgetuid_callout\fR as multipath
does not need to call any external programs here. However, under
certain circumstances udev might not be able to generate the requested
variable.
.TP
.B vpd_pg83
If none of the \fIgetuid_callout\fR or \fIuid_attribute\fR parameters
are present multipath will try to use the sysfs attribute
\fIvpd_pg83\fR to generate the wwid.
.SH "KNOWN ISSUES"
The usage of
.I queue_if_no_path
option can lead to
.I D state
processes being hung and not killable in situations where all the paths to the LUN go offline.
It is advisable to use the
.I no_path_retry
option instead.
.P
The use of
.I queue_if_no_path
or
.I no_path_retry
might lead to a deadlock if the
.I dev_loss_tmo
setting results in a device being removed while I/O is still queued.
The multipath daemon will update the
.I dev_loss_tmo
setting accordingly to avoid this deadlock. Hence if both values are
specified the order of precedence is
.I no_path_retry, queue_if_no_path, dev_loss_tmo

.SH "SEE ALSO"
.BR udev (8),
.BR dmsetup (8)
.BR multipath (8)
.BR multipathd (8)
.SH AUTHORS
.I multipath
was developed by Christophe Varoqui, <christophe.varoqui@opensvc.com> and others.
