.\" ----------------------------------------------------------------------------
.\" Update the date below if you make any significant change.
.\" Make sure there are no errors with:
.\" groff -z -wall -b -e -t multipath/multipath.8
.\"
.\" ----------------------------------------------------------------------------
.
.TH MULTIPATH 8 2016-10-26 "Linux"
.
.
.\" ----------------------------------------------------------------------------
.SH NAME
.\" ----------------------------------------------------------------------------
.
multipath \- Device mapper target autoconfig.
.
.
.\" ----------------------------------------------------------------------------
.SH SYNOPSIS
.\" ----------------------------------------------------------------------------
.
.B multipath
.RB [\| \-v\ \c
.IR verbosity \|]
.RB [\| \-b\ \c
.IR bindings_file \|]
.RB [\| \-d \|]
.RB [\| \-h | \-l | \-ll | \-f | \-t | \-F | \-B | \-c | \-q | \|-r | \|-i | \-a | \|-u | \-w | \-W \|]
.RB [\| \-p\ \c
.IR failover | multibus | group_by_serial | group_by_prio | group_by_node_name \|]
.RB [\| device \|]
.
.
.\" ----------------------------------------------------------------------------
.SH DESCRIPTION
.\" ----------------------------------------------------------------------------
.
.B multipath
is used to detect and coalesce multiple paths to devices, for fail-over or performance reasons.
.
.
.\" ----------------------------------------------------------------------------
.SH OPTIONS
.\" ----------------------------------------------------------------------------
.
.TP
.BI \-v " level"
Verbosity, print all paths and multipaths:
.RS 1.2i
.TP 1.2i
.I 0
No output.
.TP
.I 1
Print the created or updated multipath names only, for use to feed other tools like kpartx.
.TP
.I 2 +
Print all info: detected paths, coalesced paths (ie multipaths) and device maps.
.RE
.
.TP
.B \-h
Print usage text.
.
.TP
.B \-d
Dry run, do not create or update devmaps.
.
.TP
.B \-l
Show the current multipath topology from information fetched in sysfs and the device mapper.
.
.TP
.B \-ll
Show the current multipath topology from all available information (sysfs, the device mapper, path checkers ...).
.
.TP
.B \-f
Flush a multipath device map specified as parameter, if unused.
.
.TP
.B \-F
Flush all unused multipath device maps.
.
.TP
.B \-t
Print internal hardware table to stdout.
.
.TP
.B \-r
Force devmap reload.
.
.TP
.B \-i
Ignore WWIDs file when processing devices.
.
.TP
.B \-B
Treat the bindings file as read only.
.
.TP
.BI \-b " bindings_file"
Set user_friendly_names bindings file location.  The default is
\fI/etc/multipath/bindings\fR.
.
.TP
.B \-c
Check if a block device should be a path in a multipath device.
.
.TP
.B \-q
Allow device tables with \fIqueue_if_no_path\fR when multipathd is not running.
.
.TP
.B \-a
Add the WWID for the specified device to the WWIDs file.
.
.TP
.B \-u
Check if the device specified in the program environment should be
a path in a multipath device.
.
.TP
.B \-w
Remove the WWID for the specified device from the WWIDs file.
.
.TP
.B \-W
Reset the WWIDs file to only include the current multipath devices.
.
.TP
.BI \-p " policy"
Force new maps to use the specified policy:
.RS 1.2i
.TP 1.2i
.I failover
One path per priority group.
.TP
.I multibus
All paths in one priority group.
.TP
.I group_by_serial
One priority group per serial number.
.TP
.I group_by_prio
One priority group per priority value. Priorities are determined by
callout programs specified as a global, per-controller or
per-multipath option in the configuration file.
.TP
.I group_by_node_name
One priority group per target node name. Target node names are fetched
in \fI/sys/class/fc_transport/target*/node_name\fR.
.TP
.RE
Existing maps are not modified.
.
.TP
.BI device
Update only the devmap specified by
.IR device ,
which is either:
.RS 1.2i
.IP \[bu]
A devmap name.
.IP \[bu]
A path associated with the desired devmap; the path may be in one of the following formats:
.RS 1.2i
.IP \[bu]
.B /dev/sdX
.IP \[bu]
.B major:minor
.
.
.\" ----------------------------------------------------------------------------
.SH "SEE ALSO"
.\" ----------------------------------------------------------------------------
.
.BR multipathd (8),
.BR multipath.conf (5),
.BR kpartx (8),
.BR udev (8),
.BR dmsetup (8),
.BR hotplug (8).
.
.
.\" ----------------------------------------------------------------------------
.SH AUTHORS
.\" ----------------------------------------------------------------------------
.
\fImultipath-tools\fR was developed by Christophe Varoqui <christophe.varoqui@opensvc.com>
and others.
.\" EOF
