.TH MULTIPATH 8 "July 2006" "" "Linux Administrator's Manual"
.SH NAME
multipath \- Device mapper target autoconfig
.SH SYNOPSIS
.B multipath
.RB [\| \-v\ \c
.IR verbosity \|]
.RB [\| \-b\ \c
.IR bindings_file \|]
.RB [\| \-d \|]
.RB [\| \-h | \-l | \-ll | \-f | \-t | \-F | \-B | \-c | \-q | \|-r | \-w | \-W \|]
.RB [\| \-p\ \c
.BR failover | multibus | group_by_serial | group_by_prio | group_by_node_name \|]
.RB [\| device \|]
.SH DESCRIPTION
.B multipath
is used to detect and coalesce multiple paths to devices, for fail-over or performance reasons.
.SH OPTIONS
.TP
.B \-v " level"
verbosity, print all paths and multipaths
.RS 1.2i
.TP 1.2i
.B 0
no output
.TP
.B 1
print the created or updated multipath names only, for use to feed other tools like kpartx
.TP
.B 2 +
print all info : detected paths, coalesced paths (ie multipaths) and device maps
.RE
.TP
.B \-h
print usage text
.TP
.B \-d
dry run, do not create or update devmaps
.TP
.B \-l
show the current multipath topology from information fetched in sysfs and the device mapper
.TP
.B \-ll
show the current multipath topology from all available information (sysfs, the device mapper, path checkers ...)
.TP
.B \-f
flush a multipath device map specified as parameter, if unused
.TP
.B \-F
flush all unused multipath device maps
.TP
.B \-t
print internal hardware table to stdout
.TP
.B \-r
force devmap reload
.TP
.B \-B
treat the bindings file as read only
.TP
.B \-b " bindings_file"
set user_friendly_names bindings file location.  The default is
/etc/multipath/bindings
.TP
.B \-c
check if a block device should be a path in a multipath device
.TP
.B \-q
allow device tables with queue_if_no_path when multipathd is not running
.TP
.B \-w
remove the wwid for the specified device from the wwids file
.TP
.B \-W
reset the wwids file to only include the current multipath devices
.TP
.BI \-p " policy"
force new maps to use the specified policy:
.RS 1.2i
.TP 1.2i
.B failover
1 path per priority group
.TP
.B multibus
all paths in 1 priority group
.TP
.B group_by_serial
1 priority group per serial
.TP
.B group_by_prio
1 priority group per priority value. Priorities are determined by callout programs specified as a global, per-controller or per-multipath option in the configuration file
.TP
.B group_by_node_name
1 priority group per target node name. Target node names are fetched
in /sys/class/fc_transport/target*/node_name.
.TP
.RE
Existing maps are not modified.
.TP
.BI device
update only the devmap specified by
.IR device ,
which is either:
.RS 1.2i
.IP \[bu]
a devmap name
.IP \[bu]
a path associated with the desired devmap; the path may be in one of the following formats:
.RS 1.2i
.IP \[bu]
.B /dev/sdb
.IP \[bu]
.B major:minor
.SH "SEE ALSO"
.BR multipathd (8),
.BR multipath.conf (5),
.BR kpartx (8),
.BR udev (8),
.BR dmsetup (8)
.BR hotplug (8)
.SH AUTHORS
.B multipath
was developed by Christophe Varoqui, <christophe.varoqui@opensvc.com> and others.
