.TH MPATH_PRIO_ALUA 8 "7. June 2005" "multipath-tools" \
"Linux Administrator's Manual"
.SH NAME
mpath_prio_alua \- Path priority tool based on Asymmetric LUn Access
.SH SYNOPSIS
.B mpath_prio_alua
.RB [\| \-d\ \c
.IR directory \|]
.RB [\| \-h \|]
.RB [\| \-v \|]
.RB [\| \-V \|]
.IR device " \|[ " device " \|[ " ... " \|]\|]"
.SH DESCRIPTION
.B mpath_prio_alua
is used as a priority callout for the multipath command. It returns a number
that is used by multipath to group devices with the same priority together.
.SH OPTIONS
.TP
.BI \-d " directory"
target directory for devices given as relative device names or devices given
as
.IR major : minor \c
 number.
Default is "/dev".
.TP
.B \-h
displays the command line help.
.TP
.B  \-v
turns on verbose output. This shows all results in human readable format.
This includes information about the port group the device is in and its
current state.
.TP
.B  \-V
shows the version number and exits.
.TP
.BI device
specifies the device to query (the device must be a SCSI device that supports
the \*[lq]Report Target Port Groups\*[rq] command).
One of the following three formats may be used:
.RS
.IP \(bu 2
The full path name that starts with '/' (e.g. /dev/sda).
.IP \(bu
The device name only. This will prefix the directory name given by the
\-d option (e.g. sda).
.IP \(bu
The major and minor number of the device separated by ':'. This will
create a temporary device node in the device directory (e.g. 8:0). The
temporary name will be
.RB \*[lq] tmpdev-<major>:<minor>-<pid> \*[rq].
.SH "RETURN VALUE"
The mpath_prio_alua command returns the following values:
.IP \fB0
on success. In this case the priority for the device is printed to
stdout. The priority value is:
.RS
.IP \fB50\fP
for devices that are in the active, optimized group
.IP \fB10
for devices that are in an active but non-optimized group
.IP \fB1
for devices that are in the standby group
.IP \fB0
for all other groups
.RE
.IP ""
The reason for the widely spaced priority values is the way multipath handles
them. It will multiply the number of paths in a group with the priority value
and select the group with the highest result. Thus, if there are six paths in
the active, non-optimized group and only one in the active, optimized one,
the non-optimized group would be used.
.IP \fB1
Indicates an error parsing the command line.
.IP \fB2
The given devices could not be opened for reading.
.IP \fB3
The device does not support target port groups.
.IP \fB4
The inquiry command did not return a target port group for the given device.
.IP \fB5
The report target port group command failed or did not return a target
port group that was obtained from the inquiry command.
.SH "EXAMPLES"
This example queries a device directly and returns the priority string:
.P
.RS
.B #> mpath_prio_alua /dev/sda
.br
50
.RE
.P
Now the major and minor number is used to specify the device and verbose
output is selected:
.P
.RS
.B #> mpath_prio_alua -v 8:0
.br
Target port groups are implicitly supported.
.br
Reported target port group is 0 [active/optimized]
.br
50
.RE
.P
The following example shows the entries in the devices section of the
.RI "multipath-tool configuration file (" /etc/multipath.conf )
to support an IBM DS6000 storage system:
.P
.RS
.PD 0
device {
.RS
.TP 22
.B  vendor
"IBM       "
.TP
.B  product
"1750500         "
.TP
.B  path_grouping_policy
group_by_prio
.TP
.B  prio_callout
"/sbin/mpath_prio_alua -d/tmp %d"
.TP
.B  features
"1 queue_if_no_path"
.TP
.B  path_checker
tur
.RE
}
.PD
.RE
.TP
.B  Notes:
.IP \(bu 2
Depending on your default configuration not all keywords are required
.RB "(e.g. if your " path_checker " is set to tur you don't have to"
.RB "use the " path_checker " statement in the device section)."
.IP \(bu
.RB "The entries for " vendor " and " product " must be strings that are 8"
.RB "characters long (for " vendor ") and 16 characters long (for " product ")."
The strings have to be padded with blanks if necessary.
.IP \(bu
If you are working with hotpluggable devices whose device nodes are created
by udev you should use the %d flag in the
.BR prio_callout " statement."
This is because a short time elapses between the devices being available
and udev creating the device nodes.
.IP \(bu
If under certain circumstances your storage subsystem temporarily reports
.RB "failures on all paths, you should use the " features " statement showed"
in the example.
This will configure the multipath volume to requeue I/O until a path becomes
available again, instead of reporting failures in that case.
.SH "SEE ALSO"
.BR multipath (8),
.SH AUTHORS
.B mpath_prio_alua
was developed by Jan Kunigk and adapted by Stefan Bader <shbader@de.ibm.com>
