.TH KPARTX 8 "July 2006" "" "Linux Administrator's Manual"
.SH NAME
kpartx \- Create device maps from partition tables
.SH SYNOPSIS
.B kpartx
.RB [\| \-a\ \c
.BR |\ -d\ |\ -l \|]
.RB [\| \-v \|]
.RB wholedisk
.SH DESCRIPTION
This tool, derived from util-linux' partx, reads partition
tables on specified device and create device maps over partitions 
segments detected. It is called from hotplug upon device maps 
creation and deletion.
.SH OPTIONS
.TP
.B \-a
Add partition mappings
.TP
.B \-r
Read-only partition mappings
.TP
.B \-d
Delete partition mappings
.TP
.B \-u
Update partition mappings
.TP
.B \-l
List partition mappings that would be added \-a
.TP
.B \-p
set device name-partition number delimiter
.TP
.B \-f
force creation of mappings; overrides 'no_partitions' feature
.TP
.B \-g
force GUID partition table (GPT)
.TP
.B \-v
Operate verbosely
.TP
.B \-s
Sync mode. Don't return until the partitions are created
.SH EXAMPLE
To mount all the partitions in a raw disk image:
.IP
kpartx \-av disk.img
.PP
This will output lines such as:
.IP
loop3p1 : 0 20964762 /dev/loop3 63
.PP
The 
.I loop3p1
is the name of a device file under 
.I /dev/mapper
which you can use to access the partition, for example to fsck it:
.IP
fsck /dev/mapper/loop3p1
.PP
When you're done, you need to remove the devices:
.IP
kpartx \-d disk.img
.SH "SEE ALSO"
.BR multipath (8)
.BR multipathd (8)
.BR hotplug (8)
.SH "AUTHORS"
This man page was assembled By Patrick Caulfield
for the Debian project. From documentation provided
by the multipath author Christophe Varoqui, <christophe.varoqui@opensvc.com> and others.

