.TH "dmmp_path_group_status_get" 3 "dmmp_path_group_status_get" "August 2024" "Device Mapper Multipath API - libdmmp Manual" 
.SH NAME
dmmp_path_group_status_get \- Retrieve path group status.
.SH SYNOPSIS
.B "uint32_t" dmmp_path_group_status_get
.BI "(struct dmmp_path_group *" dmmp_pg ");"
.SH ARGUMENTS
.IP "dmmp_pg" 12
Pointer of 'struct dmmp_path_group'.
If this pointer is NULL, your program will be terminated by assert.
.SH "DESCRIPTION"

The valid path group statuses are:

* DMMP_PATH_GROUP_STATUS_UNKNOWN

* DMMP_PATH_GROUP_STATUS_ENABLED  -- standby to be active

* DMMP_PATH_GROUP_STATUS_DISABLED -- disabled due to all path down

* DMMP_PATH_GROUP_STATUS_ACTIVE -- selected to handle I/O
.SH "RETURN"
uint32_t.
