.TH "dmmp_path_array_get" 3 "dmmp_path_array_get" "March 2021" "Device Mapper Multipath API - libdmmp Manual" 
.SH NAME
dmmp_path_array_get \- Retrieve path pointer array.
.SH SYNOPSIS
.B "void" dmmp_path_array_get
.BI "(struct dmmp_path_group *" dmmp_pg ","
.BI "struct dmmp_path ***" dmmp_ps ","
.BI "uint32_t *" dmmp_p_count ");"
.SH ARGUMENTS
.IP "dmmp_pg" 12
Pointer of 'struct dmmp_path_group'.
If this pointer is NULL, your program will be terminated by assert.
.IP "dmmp_ps" 12
Output pointer of 'struct dmmp_path' pointer array.
If this pointer is NULL, your program will be terminated by assert.
.IP "dmmp_p_count" 12
Output pointer of uint32_t. Hold the size of 'dmmp_ps' pointer array.
If this pointer is NULL, your program will be terminated by assert.
.SH "DESCRIPTION"

The memory of output pointer array is hold by 'struct dmmp_mpath', no
need to free this memory, the resources will got freed when
\fBdmmp_mpath_array_free\fP.
.SH "RETURN"
void
