.\" ----------------------------------------------------------------------------
.\" Update the date below if you make any significant change.
.\" Make sure there are no errors with:
.\" groff -z -wall -b -e -t libmpathpersist/mpath_persistent_reserve_in.3
.\"
.\" ----------------------------------------------------------------------------
.
.TH MPATH_PERSISTENT_RESERVE_IN 3 2016-11-01 "Linux"
.
.
.\" ----------------------------------------------------------------------------
.SH NAME
.\" ----------------------------------------------------------------------------
.
mpath_persistent_reserve_in \- send PRIN command to DM device
.
.
.\" ----------------------------------------------------------------------------
.SH SYNOPSIS
.\" ----------------------------------------------------------------------------
.
.B #include <mpath_persist.h>
.P
.BI "int mpath_persistent_reserve_in" "(int fd, int rq_servact, struct prin_resp *resp, int noisy, int verbose)"
.P
.
.
.\" ----------------------------------------------------------------------------
.SH DESCRIPTION
.\" ----------------------------------------------------------------------------
.
The function in the \fBmpath_persistent_reserve_in ()\fR sends PRIN command to
the DM device and gets the response.
.TP
.B Parameters:
.RS
.TP 12
.I fd
The file descriptor of a multipath device. Input argument.
.TP
.I rq_servact
PRIN command service action. Input argument.
.TP
.I resp
The response from PRIN service action. The caller should manage the memory allocation of this structure.
.TP
.I noisy
Turn on debugging trace: Input argument. 0->Disable, 1->Enable.
.TP
.I verbose
Set verbosity level. Input argument. value:[0-3]. 0->Crits and Errors, 1->Warnings, 2->Info, 3->Debug.
.RE
.
.
.\" ----------------------------------------------------------------------------
.SH RETURNS
.\" ----------------------------------------------------------------------------
.
.TP 12
.B MPATH_PR_SUCCESS
If PR command successful.
.TP
.B MPATH_PR_SYNTAX_ERROR
If syntax error or invalid parameter.
.TP
.B MPATH_PR_SENSE_NOT_READY
If command fails with [sk,asc,ascq: 0x2,*,*].
.TP
.B MPATH_PR_SENSE_MEDIUM_ERROR
If command fails with [sk,asc,ascq: 0x3,*,*].
.TP
.B MPATH_PR_SENSE_HARDWARE_ERROR
If command fails with [sk,asc,ascq: 0x4,*,*].
.TP
.B MPATH_PR_SENSE_INVALID_OP
If command fails with [sk,asc,ascq: 0x5,0x20,0x0].
.TP
.B MPATH_PR_ILLEGAL_REQ
If command fails with [sk,asc,ascq: 0x5,*,*].
.TP
.B MPATH_PR_SENSE_UNIT_ATTENTION
If command fails with [sk,asc,ascq: 0x6,*,*].
.TP
.B MPATH_PR_SENSE_ABORTED_COMMAND
If command fails with [sk,asc,ascq: 0xb,*,*].
.TP
.B MPATH_PR_NO_SENSE
If command fails with [sk,asc,ascq: 0x0,*,*].
.TP
.B MPATH_PR_SENSE_MALFORMED
If command fails with SCSI command malformed.
.TP
.B MPATH_PR_FILE_ERROR
If command fails while accessing file (device node) problems(e.g. not found).
.TP
.B MPATH_PR_DMMP_ERROR
If Device Mapper related error.(e.g Error in getting dm info).
.TP
.B MPATH_PR_OTHER
If other error/warning has occurred(e.g transport or driver error).
.
.
.\" ----------------------------------------------------------------------------
.SH "SEE ALSO"
.\" ----------------------------------------------------------------------------
.
.BR mpathpersist (8).
.
.
.\" ----------------------------------------------------------------------------
.SH AUTHORS
.\" ----------------------------------------------------------------------------
.
\fImultipath-tools\fR was developed by Christophe Varoqui <christophe.varoqui@opensvc.com>
and others.
.\" EOF
