.\" ----------------------------------------------------------------------------
.\" Update the date below if you make any significant change.
.\" Make sure there are no errors with:
.\" groff -z -wall -b -e -t mpathpersist/mpathpersist.8
.\"
.\" ----------------------------------------------------------------------------
.
.TH MPATHPERSIST 8 2016-10-30 "Linux"
.
.
.\" ----------------------------------------------------------------------------
.SH NAME
.\" ----------------------------------------------------------------------------
.
mpathpersist \- Manages SCSI persistent reservations on dm multipath devices.
.
.
.\" ----------------------------------------------------------------------------
.SH SYNOPSIS
.\" ----------------------------------------------------------------------------
.
.B mpathpersist
.RB [\| OPTIONS \|]
.I device
.
.
.\" ----------------------------------------------------------------------------
.SH DESCRIPTION
.\" ----------------------------------------------------------------------------
.
This utility is used to manage SCSI persistent reservations on Device Mapper
Multipath devices. To be able to use this functionality, the \fIreservation_key\fR
attribute must be defined in the \fI/etc/multipath.conf\fR file. Otherwise the
\fBmultipathd\fR daemon will not check for persistent reservation for newly
discovered paths or reinstated paths.
.
.LP
\fBmpathpersist\fR supports the same command-line options as the
\fBsg_persist\fR utility.
.
Consult the \fBsg_persist (8)\fR manual page for an in-depth discussion of the
various options.
.
.\" ----------------------------------------------------------------------------
.SH OPTIONS
.\" ----------------------------------------------------------------------------
.
.TP
.BI \-verbose|\-v " level"
Verbosity:
.RS
.TP 5
.I 0
Critical messages.
.TP
.I 1
Error messages.
.TP
.I 2
Warning messages.
.TP
.I 3
Informational messages.
.TP
.I 4
Informational messages with trace enabled.
.RE
.
.TP
.BI \--device=\fIDEVICE\fB|\-d " DEVICE"
Query or change DEVICE.
.
.TP
.B \--help|\-h
Output this usage message.
.
.TP
.B \--hex|\-H
Output response in hex.
.
.TP
.B \--in|\-i
Request PR In command.
.
.TP
.B \--out|\-o
Request PR Out command.
.
.TP
.B \--param-alltgpt|\-Y
PR Out parameter 'ALL_TG_PT'.
.
.TP
.B \--param-aptpl|\-Z
PR Out parameter 'APTPL'.
.
.TP
.B \--read-keys|\-k
PR In: Read Keys.
.
.TP
.BI \--param-rk=\fIRK\fB|\-K " RK"
PR Out parameter reservation key (RK is in hex, up to 8 bytes).
.
.TP
.BI \--param-sark=\fISARK\fB|\-S " SARK"
PR Out parameter service action reservation key (SARK is in hex).
.
.TP
.B \--preempt|\-P
PR Out: Preempt.
.
.TP
.B \--clear|\-C
PR Out: Clear registrations.
.
.TP
.B \--preempt-abort|\-A
PR Out: Preempt and Abort.
.
.TP
.BI \--prout-type=\fITYPE\fB|\-T " TYPE"
PR Out command type.
.
.TP
.B \--read-full-status|\-s
PR In: Read Full Status.
.
.TP
.B \--read-keys|\-k
PR In: Read Keys.
.
.TP
.B \--read-reservation|\-r
PR In: Read Reservation.
.
.TP
.B \--register|\-G
PR Out: Register.
.
.TP
.B \--register-ignore|\-I
PR Out: Register and Ignore.
.
.TP
.B \--release|\-L
PR Out: Release.
.
.TP
.B \--report-capabilities|\-c
PR In: Report Capabilities.
.
.TP
.B \--reserve|\-R
PR Out: Reserve.
.
.TP
.BI \--transport-id=\fITIDS\fB|\-X " TIDS"
TransportIDs can be mentioned in several forms.
.
.TP
.BI \--alloc-length=\fILEN\fB|\-l " LEN"
PR In: maximum allocation length. LEN is a decimal number between 0 and 8192.
.
.
.\" ----------------------------------------------------------------------------
.SH EXAMPLE
.\" ----------------------------------------------------------------------------
.
.PP
Register the key \(dq123abc\(dq for the /dev/mapper/mpath9 device:
.RS
\fBmpathpersist --out --register --param-sark=\fI123abc /dev/mapper/mpath9\fR
.RE
.PP
Read registered reservation keys for the /dev/mapper/mpath9 device:
.RS
\fBmpathpersist -i -k \fI/dev/mapper/mpath9\fR
.RE
.PP
Create a reservation for the /dev/mapper/mpath9 device with the given
reservation key:
.RS
\fBmpathpersist --out --reserve --param-rk=\fI123abc \fB--prout-type=\fI8 \fB-d \fI/dev/mapper/mpath9\fR
.RE
.PP
Read the reservation status of the /dev/mapper/mpath9 device:
.RS
\fBmpathpersist -i -s -d \fI/dev/mapper/mpath9\fR
.RE
.PP
Release the previously created reservation (note that the prout-type needs to
be the same as above):
.RS
\fBmpathpersist --out --release --param-rk=\fI123abc \fB--prout-type=\fI8 \fB-d \fI/dev/mapper/mpath9\fR
.RE
.PP
Remove the current key registered for this host (i.e. reset it to 0):
.RS
\fBmpathpersist --out --register-ignore -K \fI123abc\fB -S \fI0\fB \fI/dev/mapper/mpath9\fR
.RE
.PP
Remove current reservation, and unregister all registered keys from all I_T nexuses:
.RS
\fBmpathpersist -oCK \fI123abc \fI/dev/mapper/mpath9\fR
.RE
.
.
.\" ----------------------------------------------------------------------------
.SH "SEE ALSO"
.\" ----------------------------------------------------------------------------
.
.BR multipath (8),
.BR multipathd (8),
.BR sg_persist (8).
.
.
.\" ----------------------------------------------------------------------------
.SH AUTHORS
.\" ----------------------------------------------------------------------------
.
\fImultipath-tools\fR was developed by Christophe Varoqui <christophe.varoqui@opensvc.com>
and others.
.\" EOF
